//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindAfternoonTea.MailServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailService.MailData", Namespace="http://schemas.datacontract.org/2004/07/FindAfternoonTea.WebServices")]
    [System.SerializableAttribute()]
    public partial class MailServiceMailData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiverAddress {
            get {
                return this.receiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverAddressField, value) != true)) {
                    this.receiverAddressField = value;
                    this.RaisePropertyChanged("receiverAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiverName {
            get {
                return this.receiverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverNameField, value) != true)) {
                    this.receiverNameField = value;
                    this.RaisePropertyChanged("receiverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string senderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.senderAddressField, value) != true)) {
                    this.senderAddressField = value;
                    this.RaisePropertyChanged("senderAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.senderNameField, value) != true)) {
                    this.senderNameField = value;
                    this.RaisePropertyChanged("senderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailServiceReference.IMailService")]
    public interface IMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/sendMail", ReplyAction="http://tempuri.org/IMailService/sendMailResponse")]
        void sendMail(FindAfternoonTea.MailServiceReference.MailServiceMailData mailData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/sendMail", ReplyAction="http://tempuri.org/IMailService/sendMailResponse")]
        System.Threading.Tasks.Task sendMailAsync(FindAfternoonTea.MailServiceReference.MailServiceMailData mailData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceChannel : FindAfternoonTea.MailServiceReference.IMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<FindAfternoonTea.MailServiceReference.IMailService>, FindAfternoonTea.MailServiceReference.IMailService {
        
        public MailServiceClient() {
        }
        
        public MailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMail(FindAfternoonTea.MailServiceReference.MailServiceMailData mailData) {
            base.Channel.sendMail(mailData);
        }
        
        public System.Threading.Tasks.Task sendMailAsync(FindAfternoonTea.MailServiceReference.MailServiceMailData mailData) {
            return base.Channel.sendMailAsync(mailData);
        }
    }
}
